#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# gen_accel_data.py -- generate a self-checking GEMM test vector header for the
# systolic-array accelerator firmware (Didactic-SoC/sw/accel/accel.c).
#
# This mirrors the methodology of sim/common/c_code/main_gemm.c (random signed
# inputs + a precomputed golden reference), but sizes the problem for the
# accelerator the firmware actually drives: a single fixed ACC_M x ACC_N x ACC_K
# pass with DATA_W-bit signed elements.
#
# The hardware computes the standard product C = A * B
#   C[i][j] = sum_k A[i][k] * B[k][j]
# with signed DATA_W x DATA_W multiplies accumulated in a 32-bit register that
# wraps in two's complement (no saturation -- see rtl/MAC/mac_pe.sv).  The golden
# reference below reproduces that exact wrap so it matches the RTL bit-for-bit,
# even when the accumulated dot product overflows 32 bits.
#
# Usage:
#   python3 sim/common/c_code/gen_accel_data.py [--seed N]
# Regenerate the header whenever the array dimensions or data width change.
# -----------------------------------------------------------------------------
import argparse
from pathlib import Path

import numpy as np

# Accelerator build parameters (must match accelerator_top: M=N=K=16, DATA_W=16,
# ACC_W=32).
ACC_M = 16
ACC_N = 16
ACC_K = 16
ACC_DATA_W = 16
ACC_ACC_W = 32

DEFAULT_SEED = 0xACCE
# This file lives at sim/common/c_code/gen_accel_data.py, so the repo root is
# four parents up; the generated header lands in the Didactic-SoC submodule.
OUT_PATH = (
    Path(__file__).resolve().parents[3]
    / "Didactic-SoC"
    / "sw"
    / "accel"
    / "accel_gemm_data.h"
)


def wrap_signed(values: np.ndarray, bits: int) -> np.ndarray:
    """Reduce integer values into a signed two's-complement field of `bits`."""
    mod = 1 << bits
    half = 1 << (bits - 1)
    return ((values + half) % mod) - half


def fmt_rows(flat: np.ndarray, cols: int, indent: str = "    ") -> str:
    """Format a flat array as comma-separated rows of `cols` values."""
    lines = []
    for r in range(0, len(flat), cols):
        chunk = ", ".join(str(int(v)) for v in flat[r : r + cols])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--seed",
        type=lambda s: int(s, 0),
        default=DEFAULT_SEED,
        help=f"PRNG seed (default 0x{DEFAULT_SEED:X})",
    )
    args = ap.parse_args()

    rng = np.random.default_rng(args.seed)
    lo = -(1 << (ACC_DATA_W - 1))
    hi = 1 << (ACC_DATA_W - 1)  # exclusive upper bound -> max = hi - 1

    # Random signed DATA_W-bit operands. int64 keeps the matmul exact before the
    # explicit 32-bit wrap below.
    a = rng.integers(lo, hi, size=(ACC_M, ACC_K), dtype=np.int64)
    b = rng.integers(lo, hi, size=(ACC_K, ACC_N), dtype=np.int64)

    # Golden product with the same two's-complement 32-bit wrap as the RTL MAC.
    c = wrap_signed(a @ b, ACC_ACC_W)

    a_flat = a.reshape(-1)  # row-major A[i*K + k]
    b_flat = b.reshape(-1)  # row-major B[k*N + j]
    c_flat = c.reshape(-1)  # row-major C[i*N + j]

    header = f"""\
#ifndef __ACCEL_GEMM_DATA_H__
#define __ACCEL_GEMM_DATA_H__

#include <stdint.h>

/*
 * Auto-generated by sim/common/c_code/gen_accel_data.py (seed 0x{args.seed:X}).
 * Do not edit by hand; rerun the generator instead.
 *
 * Random signed {ACC_DATA_W}-bit GEMM test vectors for the systolic-array
 * accelerator.  The golden matrix is C = A * B with
 *   C[i][j] = sum_k A[i][k] * B[k][j]
 * accumulated in 32-bit two's-complement arithmetic (wraps, no saturation),
 * matching rtl/MAC/mac_pe.sv exactly.
 *
 * Layout (row-major, matching the hardware buffers):
 *   A[i][k] -> accel_A[i * ACC_K + k]
 *   B[k][j] -> accel_B[k * ACC_N + j]
 *   C[i][j] -> accel_golden[i * ACC_N + j]
 */

#define ACC_M {ACC_M}
#define ACC_N {ACC_N}
#define ACC_K {ACC_K}
#define ACC_DATA_W {ACC_DATA_W}

static const int16_t accel_A[ACC_M * ACC_K] = {{
{fmt_rows(a_flat, ACC_K)}
}};

static const int16_t accel_B[ACC_K * ACC_N] = {{
{fmt_rows(b_flat, ACC_N)}
}};

static const int32_t accel_golden[ACC_M * ACC_N] = {{
{fmt_rows(c_flat, ACC_N)}
}};

#endif /* __ACCEL_GEMM_DATA_H__ */
"""

    OUT_PATH.write_text(header)
    print(f"wrote {OUT_PATH} (seed 0x{args.seed:X}, {ACC_M}x{ACC_N}x{ACC_K})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
