TOPLEVEL := matrix_buffer_c
MODULE   := test_matrix_buffer_c

REPO_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/../../..)
VERILOG_SOURCES := $(REPO_ROOT)/rtl/matrix/matrix_buffer_c.sv

COCOTB_TB_DIR := $(REPO_ROOT)/sim/testbenches/matrix_c

include $(REPO_ROOT)/sim/scripts/Makefile.common
